---
title: ""
author: 
  name: Lisa Avery
  institute: "Biostatistics@UHN" 
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    fig-height: 4
    fig-width: 6.5
    toc: TRUE
  docx:
    fig-height: 4
    fig-width: 6.5
    reference-doc: 'wordTemplate.docx'
  pdf:
    toc: TRUE
    fig-height: 4
    fig-width: 6.5
output-dir: .
format-links: false
bibliography: bibfile.bib  
editor: source
execute: 
  echo: false
  warning: false
  message: false
knitr:
  opts_chunk: 
    comment: ""
    dpi: 300     
---

```{r setup}
#| include: false
library(tidyverse)
library(janitor)
library(reportRmd)

theme_pmh <- function(base_size=10){
  theme_bw(base_size=base_size)  %+replace% 
    theme(
    legend.position = 'bottom',
    plot.title = element_text(size = base_size, face = "plain",hjust = 0),
    legend.key.width = unit(1, "lines"),
    legend.text = element_text(
      margin = margin(l = -.5)
    ))
}
theme_set(theme_pmh(base_size=10))
options(list(ggplot2.discrete.fill = function() reportRmd:::scale_colour_reportRx(),
             ggplot2.discrete.colour = function() reportRmd:::scale_colour_reportRx()))
R_version <- paste(sessionInfo()[1]$R.version$major,sessionInfo()[1]$R.version$minor,sep=".")
set.seed(2025)
source( "R/format_utils.R")
source( "R/correlations.R")
source( "R/data_cleaning.R")
source( "R/data_import.R")
source( "R/data_screening.R")
source( "R/deid_functions.R")
source( "R/durations.R")
source( "R/marker_selection.R")
source( "R/model_eval.R")
source( "R/pet_mri_functions.R")

source( "R/quarto_tools.R")
source( "R/redcap.R")

```

```{r}
#| eval: false
#| include: false
Rmisc::createBibFile("bibout.bib")
```

# Document History

**Date**

First draft

# Statistical Analysis

Statistical analyses were conducted using the R statistical programming language version `r R_version` [@R-base].

# Results


# References
-->
::: {#refs}
:::

# Appendix: Software
```{r}
reportRmd::extract_package_details() |> 
  filter(!package_name %in% c("reportRmd","Rmisc")) |> 
  outTable()


```

