# data_import.R
# Dictionary-driven Excel import pipeline: typed/labelled import, date
# detection and conversion, dictionary creation, and diagnostic accessors.
# Self-contained (no external source() calls, no library() side effects).
#
# Suggests packages: readxl, janitor, lubridate, rlang, dplyr, tidyr, tibble


# ---- Internal helpers used across the file ----

#' Conditionally emit a message
#'
#' Wraps \code{message()} so that progress messages can be silenced via a
#' single \code{verbose = FALSE} argument on the public functions.
#'
#' @param verbose Logical scalar.
#' @param ... Passed to \code{message()}.
#' @keywords internal
msg_if <- function(verbose, ...) {
  if (isTRUE(verbose)) message(...)
}


#' Create a class-tagged importExcel result tibble
#'
#' Attaches diagnostics as attributes and prepends the \code{importExcel_df}
#' class so accessors (and a future print method) can recognise it.
#'
#' @param data A data frame.
#' @param ... Named diagnostic objects to attach as attributes.
#' @keywords internal
new_import_result <- function(data, ...) {
  attrs <- list(...)
  for (nm in names(attrs)) {
    attr(data, nm) <- attrs[[nm]]
  }
  class(data) <- unique(c("importExcel_df", class(data)))
  data
}


#' Create a coded and labelled data frame from an Excel File
#'
#' @description
#' Creates a cleaned, labelled and coded data set from Excel data that has been
#' processed with the excel data checker. This function performs comprehensive
#' data cleaning including type conversion, factor creation, and date parsing
#' based on instructions provided in a data dictionary sheet.
#'
#' @details
#' The dictionary sheet must contain the following columns:
#' \itemize{
#'   \item \code{Current_Variable_Name} - column name as it appears in the data sheet
#'   \item \code{Suggested_Name} - cleaned variable name to use in R
#'   \item \code{Label_For_Report} - human-readable label for reporting
#'   \item \code{Type} - one of "Codes", "Categorical", "Numeric", "Date", or other
#'   \item \code{Value} - level values (for Codes and Categorical types)
#'   \item \code{Value_Label} - labels for each level (for Codes and Categorical)
#'   \item \code{Column_Number} - position of the column in the data sheet
#'   \item \code{Import} - (optional) logical; FALSE drops the column from the result
#' }
#'
#' @param data_file Character. Full path to the Excel file to be imported.
#' @param data_sheet Character. Exact name of the sheet containing the data.
#' @param dictionary_sheet Character. Name of the sheet containing the data
#'   dictionary formatted by the PMHbiostats macro.
#' @param na Character vector. Strings to interpret as missing values in both
#'   the dictionary and the data. Default is empty string (\code{""}).
#' @param verbose Logical. If \code{TRUE} (default), emit progress messages
#'   as the import proceeds. Set to \code{FALSE} for quiet imports inside
#'   reports or pipelines.
#'
#' @return A tibble of class \code{importExcel_df}: the coded, labelled
#'   data frame with diagnostics attached as attributes. Use the helper
#'   accessors to retrieve them:
#'   \describe{
#'     \item{\code{import_warnings(x)}}{Warnings generated by \pkg{readxl}.}
#'     \item{\code{numeric_conversions(x)}}{Tibble of non-numeric values
#'       removed during numeric conversion (\code{variable},
#'       \code{values_removed}, \code{n}).}
#'     \item{\code{date_warnings(x)}}{Wide tibble of date-conversion
#'       issues (\code{variable}, \code{n_errors}, \code{multiple_formats},
#'       \code{n_future_dates}, \code{error_values}).}
#'     \item{\code{import_dictionary(x)}}{The updated data dictionary.}
#'     \item{\code{import_summary(x)}}{Per-variable summary of actions
#'       taken, suitable for \code{knitr::kable()}.}
#'   }
#'
#' @examples
#' \dontrun{
#' df <- read_excel_with_dictionary(
#'   data_file = "path/to/data.xlsx",
#'   data_sheet = "Data",
#'   dictionary_sheet = "Dictionary"
#' )
#'
#' # df is the cleaned data frame; diagnostics live as attributes
#' import_summary(df)
#' numeric_conversions(df)
#' date_warnings(df)
#' }
#'
#' @importFrom readxl read_excel excel_sheets
#' @importFrom janitor excel_numeric_to_date
#' @importFrom lubridate dmy mdy ymd
#' @importFrom rlang sym
#' @export
read_excel_with_dictionary <- function(data_file,
                                       data_sheet,
                                       dictionary_sheet,
                                       na = "",
                                       verbose = TRUE) {

  # Check that the file exists ----
  if (!file.exists(data_file)) {
    stop(sprintf("Data file not found: '%s'\nPlease check the file path.",
                 data_file))
  }

  # Check that the requested sheets exist in the file ----
  sht_nms <- readxl::excel_sheets(data_file)
  if (!(data_sheet %in% sht_nms)) {
    stop("The data sheet is not a sheet in the data file")
  }
  if (!(dictionary_sheet %in% sht_nms)) {
    stop("The dictionary sheet is not a sheet in the data file")
  }

  # Read the dictionary sheet ----
  dict_import <- read_excel_with_warnings(data_file, dictionary_sheet, na)
  dictionary <- dict_import$data

  # Trim trailing rows from older versions of the Excel macro ----
  # Older versions appended a list of text-only variables after a marker row.
  last_ln_txt <- "The following variables are mostly text and should not be imported:"
  last_ln <- which(dictionary$Current_Variable_Name == last_ln_txt)
  if (length(last_ln) > 0) dictionary <- dictionary[1:(last_ln - 1), ]

  # Read the data sheet ----
  imported_data <- suppressMessages(
    read_excel_with_warnings(data_file, data_sheet, na)
  )
  if (is.null(imported_data$data)) {
    stop(paste("Error reading the data:\n", imported_data$errorMsg))
  }
  new_data <- imported_data$data

  # Identify columns with empty names ----
  # readxl assigns names like '...1', '...2' to columns with empty headers.
  # These columns will be absent from the dictionary and must be dropped.
  to_rm <- which(grepl("^\\.{3}", names(new_data)))

  # Verify that the data column names match the dictionary ----
  data_names_clean <- gsub("\\.{3}.*", "",
                           names(new_data)[setdiff(seq_len(ncol(new_data)), to_rm)])
  dict_names <- na.omit(dictionary$Current_Variable_Name)
  if (!all(data_names_clean == dict_names)) {
    stop("The column names in the data do not exactly match the Current_Variable_Name in the dictionary.\nDid you specify the correct data and dictionary sheets?")
  }

  # Warn about empty column names ----
  if (length(to_rm) > 0) {
    warning(paste("Empty column name(s) found in column(s)",
                  paste(to_rm, collapse = ", "),
                  ". These columns will not be imported.\nTo import add a column name and re-run the dataChecker macro to update the dictionary."))
  }

  # Ensure variable names don't start with "_" ----
  had_underscored_name <- FALSE
  for (sn in na.omit(dictionary$Suggested_Name)) {
    if (substr(sn, 1, 1) == "_") {
      dictionary$Suggested_Name[which(dictionary$Suggested_Name == sn)] <- sub("_", "v", sn)
      had_underscored_name <- TRUE
    }
  }
  if (had_underscored_name) {
    msg_if(verbose, "Suggested names beginning with '_' were replaced with 'v'.\nRefer to updated dictionary.")
  }

  # Rename data columns using Suggested_Name from the dictionary ----
  for (v in setdiff(seq_len(ncol(new_data)), to_rm)) {
    new_name <- dictionary$Suggested_Name[which(dictionary$Column_Number == v)]

    if (length(new_name) == 0 || is.na(new_name)) {
      if ("Import" %in% names(dictionary)) {
        import_flag <- dictionary$Import[which(dictionary$Column_Number == v)]
        if (length(import_flag) > 0 && isTRUE(import_flag)) {
          stop(paste("The suggested name for column number", v,
                     "is empty.\nPlease add a column name to the dictionary for this variable before import."))
        } else {
          new_name <- "to_be_deleted"
        }
      }
    }

    # Skip if there's no usable name and the column is already flagged for removal
    if (!(v %in% to_rm && length(new_name) == 0)) {
      to_rm <- setdiff(to_rm, v)
      # Trim a trailing underscore from suggested names
      if (nchar(new_name) > 0 && substr(new_name, nchar(new_name), nchar(new_name)) == "_") {
        new_name <- substr(new_name, 1, nchar(new_name) - 1)
        dictionary$Suggested_Name[which(dictionary$Column_Number == v)] <- new_name
      }
      if (length(new_name) > 0 && !is.na(new_name)) {
        names(new_data)[v] <- new_name
      }
    }
  }

  # Drop columns flagged by the Import column or with empty names ----
  # NA in Import is treated as "keep" here; tidyr::fill() below forward-fills
  # NAs so that subsequent operations see a complete Import flag.
  if ("Import" %in% names(dictionary)) {
    import_to_rm <- na.omit(dictionary[["Column_Number"]][!dictionary$Import])
    to_rm <- unique(c(to_rm, import_to_rm))
    if (length(to_rm) > 0) new_data <- new_data[, -to_rm]
    dictionary <- dictionary |>
      tidyr::fill(Import) |>
      dplyr::filter(Import)
  } else {
    if (length(to_rm) > 0) new_data <- new_data[, -to_rm]
  }

  # Disambiguate duplicated variable names ----
  if (any(duplicated(names(new_data)))) {
    msg_if(verbose, "Duplicated variable names found.\nTo prevent this ensure distinct values in the Suggested_Name column in the data dictionary.")
    first_dupl <- which(duplicated(names(new_data)))[1]
    repeat {
      dupl_nm <- names(new_data)[first_dupl]
      dupl_ind <- which(names(new_data) == dupl_nm)
      new_names <- paste0(dupl_nm, "_", seq_along(dupl_ind))
      names(new_data)[dupl_ind] <- new_names
      # Update the dictionary entries that previously had this Suggested_Name
      dict_rows <- which(dictionary$Suggested_Name == dupl_nm)
      if (length(dict_rows) == length(new_names)) {
        dictionary$Suggested_Name[dict_rows] <- new_names
      }
      if (!any(duplicated(names(new_data)))) break
      first_dupl <- which(duplicated(names(new_data)))[1]
    }
  }

  # Convert coded variables to factors ----
  msg_if(verbose, "Converting coded columns to factors.....")
  fct_variables <- dplyr::pull(
    dplyr::filter(dictionary, Type == "Codes"),
    Suggested_Name
  )
  for (v in fct_variables) {
    if (!(v %in% names(new_data))) {
      stop(paste(v, "not found in data - check dictionary spelling and column number"))
    }
    lvl_lbl <- dplyr::select(
      dplyr::filter(
        tidyr::fill(dictionary, Suggested_Name, .direction = "down"),
        Suggested_Name == v
      ),
      Value, Value_Label
    )
    if (any(!is.na(lvl_lbl$Value_Label))) {
      lvl_lbl <- lvl_lbl |>
        dplyr::filter(!is.na(Value_Label))
      n_f <- try(
        factor(new_data[[v]], levels = lvl_lbl$Value, labels = lvl_lbl$Value_Label),
        silent = TRUE
      )
      if (!inherits(n_f, "try-error")) {
        new_data[[v]] <- n_f
      } else {
        warning(paste0("Error coding ", v, ". Check for missing values in dictionary.\nVariable not recoded."))
      }
    }
  }

  # Convert categorical variables to factors ----
  msg_if(verbose, "Converting categorical columns to factors .....")
  cat_variables <- dplyr::pull(
    dplyr::filter(dictionary, Type == "Categorical"),
    Suggested_Name
  )
  for (v in cat_variables) {
    if (!(v %in% names(new_data))) {
      stop(paste(v, "not found in data - check dictionary spelling and column number"))
    }
    lvl_lbl <- dplyr::select(
      dplyr::filter(
        tidyr::fill(dictionary, Suggested_Name, .direction = "down"),
        Suggested_Name == v
      ),
      Value, Value_Label
    ) |>
      dplyr::distinct()

    # Check for duplicate values - this can happen with trailing whitespace
    if (any(duplicated(lvl_lbl$Value))) {
      stop(paste("Duplicated variable values found in", v, ".\nCheck the data dictionary."))
    }
    if (any(!is.na(lvl_lbl$Value_Label))) {
      lvl_lbl <- lvl_lbl |>
        dplyr::filter(!is.na(Value_Label))
      n_f <- try(
        factor(new_data[[v]], levels = lvl_lbl$Value, labels = lvl_lbl$Value_Label),
        silent = TRUE
      )
    } else {
      n_f <- try(factor(new_data[[v]], levels = lvl_lbl$Value), silent = TRUE)
    }
    if (!inherits(n_f, "try-error")) {
      new_data[[v]] <- n_f
    } else {
      warning(paste("Error converting", v, "to factor. Check for missing values in dictionary.\nVariable not recoded."))
    }
  }

  # Convert numeric variables and strip any text ----
  msg_if(verbose, "Converting numeric columns.....")
  num_variables <- dplyr::pull(
    dplyr::filter(dictionary, Type == "Numeric"),
    Suggested_Name
  )
  num_conversions <- NULL
  for (v in num_variables) {
    if (!(v %in% names(new_data))) {
      stop(paste(v, "not found in data - check dictionary spelling and column number"))
    }
    orig <- new_data[[v]]
    num_data <- suppressWarnings(as.numeric(orig))
    na_orig <- which(is.na(orig))
    na_new  <- which(is.na(num_data))
    new_data[[v]] <- num_data
    # Values that became NA after conversion (i.e. non-numeric) ----
    coerced_to_na <- setdiff(na_new, na_orig)
    if (length(coerced_to_na) > 0) {
      num_conversions <- dplyr::bind_rows(
        num_conversions,
        tibble::tibble(
          variable = v,
          values_removed = paste(unique(orig[coerced_to_na]), collapse = ", "),
          n = length(coerced_to_na)
        )
      )
    }
  }

  # Convert date columns ----
  msg_if(verbose, "Converting date columns.....")
  dict_date_vars <- dplyr::pull(
    dplyr::filter(dictionary, Type == "Date"),
    Suggested_Name
  )
  dt_conversions <- NULL

  for (v in dict_date_vars) {
    if (!(v %in% names(new_data))) {
      stop(paste(v, "not found in data - check dictionary spelling and column number"))
    }
    result <- convert_column_to_date(new_data[[v]], var_name = v)
    new_data[[v]] <- result$parsed
    if (result$n_errors > 0 || result$multiple_formats || result$n_future_dates > 0) {
      dt_conversions <- dplyr::bind_rows(
        dt_conversions,
        tibble::tibble(
          variable         = v,
          n_errors         = result$n_errors,
          multiple_formats = result$multiple_formats,
          n_future_dates   = result$n_future_dates,
          error_values     = paste(result$error_values, collapse = ", ")
        )
      )
    }
  }

  # Apply variable labels for reporting ----
  new_data <- reportRmd::set_labels(
    new_data,
    dplyr::select(dictionary, Suggested_Name, Label_For_Report)
  )

  # One-line summary, if requested ----
  n_num <- if (is.null(num_conversions)) 0L else nrow(num_conversions)
  n_dt  <- if (is.null(dt_conversions))  0L else nrow(dt_conversions)
  msg_if(verbose, sprintf("Imported %d columns; %d numeric conversion(s), %d date warning(s).",
                          ncol(new_data), n_num, n_dt))

  new_import_result(
    new_data,
    import_warnings     = imported_data$warnings,
    numeric_conversions = num_conversions,
    date_warnings       = dt_conversions,
    import_dictionary   = dictionary
  )
}


#' Read an Excel sheet and capture warnings
#'
#' @description
#' Wrapper around \code{readxl::read_excel()} that collects warnings into a list
#' rather than emitting them, and traps errors so the caller can react to a
#' read failure without halting.
#'
#' @param data_file Character. Path to the Excel file.
#' @param data_sheet Character. Name of the sheet to read.
#' @param na Character vector. Strings to interpret as missing values.
#'
#' @return A list with elements \code{data} (the imported tibble or NULL on
#'   failure), \code{warnings} (a list of warning messages collected during
#'   import), and \code{errorMsg} (NULL on success, or the error condition).
#'
#' @keywords internal
read_excel_with_warnings <- function(data_file, data_sheet, na) {

  # Save and restore the user's warn option ----
  old_warn <- getOption("warn")
  on.exit(options(warn = old_warn), add = TRUE)
  options(warn = -1)

  warnings_list <- list()
  errorMsg <- NULL
  data <- NULL

  result <- try({
    withCallingHandlers({
      readxl::read_excel(data_file, sheet = data_sheet, na = na)
    }, warning = function(w) {
      warnings_list <<- c(warnings_list, conditionMessage(w))
      invokeRestart("muffleWarning")
    })
  }, silent = TRUE)

  if (inherits(result, "try-error")) {
    errorMsg <- attr(result, "condition")$message
    warning("An error occurred while reading the Excel file.")
  } else {
    data <- result
  }

  list(data = data, warnings = warnings_list, errorMsg = errorMsg)
}


#' Read an Excel sheet with multi-row headers
#'
#' @description
#' Reads an Excel sheet whose header spans either two or three rows, and
#' collapses the rows into a single set of column names. Group labels in the
#' upper header row(s) are forward-filled across merged cells (\code{NA}s
#' produced by \code{readxl}'s \code{...N} placeholders) so that each column
#' inherits its parent group. When \code{clean_names = TRUE} (default), the
#' collapsed names are cleaned via \code{janitor::clean_names()} and the
#' original combined names are preserved as \code{label} attributes on each
#' column via \code{set_names_as_labels()}.
#'
#' @details
#' For a sheet structured like:
#' \preformatted{
#'   Demographics    |               | Lab results          |
#'   Age             | Sex           | Hemoglobin | Glucose |
#'   45              | M             | 13.2       | 5.4     |
#' }
#' the resulting column names would be roughly
#' \code{c("demographics_age", "demographics_sex", "lab_results_hemoglobin",
#'   "lab_results_glucose")} after cleaning, with the un-cleaned combined
#' names retained as \code{label} attributes.
#'
#' @param data_file Character. Path to the Excel file.
#' @param sheet Character. Name of the sheet to read.
#' @param header_rows Integer. Number of header rows to combine; must be 2 or 3.
#'   Default is 2.
#' @param na Character vector. Strings to interpret as missing values. Default
#'   is \code{c("na", "NA")}.
#' @param clean_names Logical. If \code{TRUE} (default), apply
#'   \code{set_names_as_labels()} to clean the column names and store the
#'   originals as labels.
#'
#' @return A tibble with one row per data row and one column per leaf header,
#'   named by combining the (forward-filled) upper header(s) with the bottom
#'   header row.
#'
#' @examples
#' \dontrun{
#' # Two-row header
#' lab_results <- read_excel_multi_header(
#'   data_file = "data.xlsx",
#'   sheet = "Lab results",
#'   header_rows = 2
#' )
#'
#' # Three-row header
#' visits <- read_excel_multi_header(
#'   data_file = "data.xlsx",
#'   sheet = "Visits",
#'   header_rows = 3
#' )
#' }
#'
#' @importFrom readxl read_excel
#' @importFrom janitor make_clean_names
#' @export
read_excel_multi_header <- function(data_file,
                                    sheet,
                                    header_rows = 2,
                                    na = c("na", "NA"),
                                    clean_names = TRUE) {

  # Validate inputs ----
  if (!file.exists(data_file)) {
    stop(sprintf("Data file not found: '%s'\nPlease check the file path.", data_file))
  }
  if (!sheet %in% readxl::excel_sheets(data_file)) {
    stop(sprintf("Sheet '%s' not found in '%s'.", sheet, data_file))
  }
  if (!header_rows %in% c(2, 3)) {
    stop("`header_rows` must be either 2 or 3.")
  }

  # Helper to extract a single header row as a character vector ----
  # Reads `skip` rows, treats the next row as the header, then returns its
  # names. readxl assigns names like '...N' to empty/merged cells; these are
  # converted to NA so na_fill() can carry the previous label forward.
  read_header_row <- function(skip_n) {
    tmp <- readxl::read_excel(
      data_file,
      sheet  = sheet,
      skip   = skip_n,
      n_max  = 1,
      na     = na
    )
    nm <- names(tmp)
    nm[grepl("^\\.{3}", nm)] <- NA
    # Strip the '...N' suffix that readxl appends to disambiguate duplicates
    nm <- gsub("\\.{3}.*", "", nm)
    nm
  }

  # Read each header row ----
  upper_rows <- lapply(seq_len(header_rows - 1) - 1, read_header_row)

  # Read the bottom header row, which is the actual data import ----
  data_out <- readxl::read_excel(
    data_file,
    sheet = sheet,
    skip  = header_rows - 1,
    na    = na
  )
  bottom <- names(data_out)
  bottom[grepl("^\\.{3}", bottom)] <- NA
  bottom <- gsub("\\.{3}.*", "", bottom)

  # Forward-fill each upper row so group labels propagate across merged cells ----
  upper_filled <- lapply(upper_rows, function(nm) {
    # na_fill keeps any leading NAs as NA (no carry-from-the-right)
    as.character(na_fill(nm))
  })

  # Pad each header vector to the width of the data, then combine ----
  n_cols <- length(bottom)
  pad_to_width <- function(x) {
    length(x) <- n_cols
    x
  }
  upper_filled <- lapply(upper_filled, pad_to_width)

  # Combine the rows column-wise into a single name with " " as separator ----
  # NA components are dropped so a leaf with no upper label uses just its own name
  combined <- vapply(seq_len(n_cols), function(i) {
    parts <- c(vapply(upper_filled, `[`, character(1), i), bottom[i])
    parts <- parts[!is.na(parts) & nzchar(parts)]
    trimws(paste(parts, collapse = " "))
  }, character(1))

  names(data_out) <- combined

  # Optionally clean names and store originals as labels ----
  if (clean_names) {
    data_out <- set_names_as_labels(data_out)
  }

  data_out
}


#' Parse a single date value across multiple formats
#'
#' @description
#' Attempts to parse a single value as a date. Excel-style numeric dates
#' (5-digit serials) are handled first via \code{janitor::excel_numeric_to_date()};
#' character values are tried as dmy, then mdy, then ymd via \pkg{lubridate}.
#'
#' @param x A length-one value (character or numeric) to parse.
#'
#' @return A one-row data frame with columns \code{original}, \code{parsed}
#'   (as character, yyyy-mm-dd), \code{format} (one of "Date", "excelNumeric",
#'   "dmy", "mdy", "ymd", or "error"), and \code{parsing} (the lubridate
#'   message describing the matched format, or "none" on failure).
#'
#' @keywords internal
parse_date <- function(x) {

  # Save and restore options ----
  old_warn <- getOption("warn")
  old_lub  <- getOption("lubridate.verbose")
  on.exit({
    options(warn = old_warn)
    options(lubridate.verbose = old_lub)
  }, add = TRUE)
  options(warn = -1)
  options(lubridate.verbose = TRUE)

  # Handle NA / empty / non-scalar input ----
  if (length(x) != 1L || is.na(x) || (is.character(x) && !nzchar(trimws(x)))) {
    return(data.frame(original = NA, parsed = NA, format = NA, parsing = NA))
  }

  orig_value <- x
  dt <- NA
  dt_type <- NULL
  parsing_format <- NA_character_

  if (is.numeric(x)) {
    # Numeric input - always treat as an Excel serial date ----
    # (Bypasses the 5-digit length check used for character disambiguation.)
    dt <- try(janitor::excel_numeric_to_date(x), silent = TRUE)
    if (!inherits(dt, "try-error") && !is.na(dt)) {
      dt_type <- "excelNumeric"
      parsing_format <- "excel_numeric_to_date"
    } else {
      dt_type <- "error"
      parsing_format <- "none"
      dt <- NA
    }
  } else if (is_num_dt(x)) {
    # 5-digit character that looks like an Excel serial ----
    dt <- try(as.Date(x), silent = TRUE)
    if (!inherits(dt, "try-error") && !is.na(dt)) {
      dt_type <- "Date"
      parsing_format <- "as.Date"
    } else {
      dt <- try(janitor::excel_numeric_to_date(as.numeric(x)), silent = TRUE)
      if (!inherits(dt, "try-error") && !is.na(dt)) {
        dt_type <- "excelNumeric"
        parsing_format <- "excel_numeric_to_date"
      } else {
        dt_type <- "error"
        parsing_format <- "none"
        dt <- NA
      }
    }
  } else {
    # Character date - try dmy, then mdy, then ymd ----
    try_format <- function(fn) {
      msgs <- capture.output(
        parsed <- try(fn(trimws(as.character(x))), silent = TRUE),
        type = "message"
      )
      list(parsed = parsed, msgs = paste(msgs, collapse = ";"))
    }

    res <- try_format(lubridate::dmy)
    if (!inherits(res$parsed, "try-error") && !is.na(res$parsed)) {
      dt <- res$parsed; dt_type <- "dmy"; parsing_format <- res$msgs
    } else {
      res <- try_format(lubridate::mdy)
      if (!inherits(res$parsed, "try-error") && !is.na(res$parsed)) {
        dt <- res$parsed; dt_type <- "mdy"; parsing_format <- res$msgs
      } else {
        res <- try_format(lubridate::ymd)
        if (!inherits(res$parsed, "try-error") && !is.na(res$parsed)) {
          dt <- res$parsed; dt_type <- "ymd"; parsing_format <- res$msgs
        } else {
          dt_type <- "error"; parsing_format <- "none"; dt <- NA
        }
      }
    }
  }

  out <- data.frame(
    original = as.character(orig_value),
    parsed   = as.character(dt),
    format   = dt_type,
    parsing  = parsing_format
  )
  if (nrow(out) > 0) out |> dplyr::slice_head(n = 1) else out
}


#' Clean and reconcile parsed dates
#'
#' @description
#' Takes the output of \code{parse_date()} applied to a column of values and
#' decides whether multiple formats were present, whether any values failed to
#' parse, and whether any ambiguous formats (e.g. both dmy and mdy matching
#' different rows) should be flagged.
#'
#' @param parsed_date A data frame with columns \code{original}, \code{parsed},
#'   \code{format}, and \code{parsing}, as produced by \code{parse_date()}.
#'
#' @return A list with:
#'   \describe{
#'     \item{errors}{Logical. TRUE if any value failed to parse or ambiguity
#'       was detected.}
#'     \item{multiple_formats}{Logical. TRUE if more than one date format
#'       was matched across the column.}
#'     \item{cleaned_dates}{A data frame with the original and parsed values,
#'       plus a \code{date_check} column when multiple formats were detected.}
#'   }
#'
#' @keywords internal
clean_dates <- function(parsed_date) {
  multiple_formats <- FALSE
  errors <- FALSE
  if (!all(names(parsed_date) == c("original", "parsed", "format", "parsing"))) {
    stop("Parsed date must be data output from parse_date()")
  }
  format_types <- data.frame(with(parsed_date, table(parsing, format))) |>
    dplyr::filter(Freq != 0)

  format_types_no_error <- format_types |>
    dplyr::filter(format != "error")

  if (nrow(format_types_no_error) != nrow(format_types)) {
    errors <- TRUE
  }
  if (nrow(format_types_no_error) > 1) {
    multiple_formats <- TRUE
  }

  # Detect ambiguity: same format produced by multiple parsing strings ----
  format_dupl <- data.frame(with(format_types_no_error, table(format))) |>
    dplyr::filter(Freq > 1)
  if (nrow(format_dupl) > 0) {
    errors <- TRUE
    bad_prs <- format_types_no_error |>
      dplyr::filter(format %in% format_dupl$format) |>
      dplyr::mutate(l_prs = nchar(as.character(parsing))) |>
      dplyr::group_by(format) |>
      dplyr::slice_max(n = 1, order_by = l_prs) |>
      dplyr::mutate(parsing = as.character(parsing)) |>
      dplyr::pull(parsing)
    parsed_date <- parsed_date |>
      dplyr::mutate(parsed = ifelse(parsing %in% bad_prs, NA, parsed))
  }

  if (multiple_formats) {
    parsed_date <- parsed_date |>
      dplyr::mutate(date_check = format(lubridate::ymd(parsed), "%Y-%b-%d"))
  }

  # Convert parsed back to Date class for downstream use ----
  parsed_date <- parsed_date |>
    dplyr::mutate(parsed = suppressWarnings(lubridate::ymd(parsed)))

  out <- parsed_date |>
    dplyr::select(dplyr::any_of(c("original", "parsed", "date_check")))

  list(errors = errors, multiple_formats = multiple_formats, cleaned_dates = out)
}


#' Test whether a value looks like an Excel numeric date serial
#'
#' @description
#' Excel stores dates as 5-digit numeric serials. This helper returns
#' \code{TRUE} when the input can be coerced to numeric and is exactly five
#' characters long.
#'
#' @param x A length-one value.
#'
#' @return Logical scalar.
#'
#' @keywords internal
is_num_dt <- function(x) {
  if (length(x) != 1L || is.na(x)) return(FALSE)
  num <- suppressWarnings(as.numeric(x))
  !is.na(num) && nchar(as.character(x)) == 5
}


#' Forward-fill NA values in a vector
#'
#' @description
#' Replaces each \code{NA} with the most recent non-\code{NA} value preceding
#' it. Leading \code{NA}s (those occurring before any non-\code{NA} value) are
#' left as \code{NA}. This is a lightweight, dependency-free replacement for
#' \code{zoo::na.locf(x, na.rm = FALSE)} suitable for cleaning up merged-cell
#' header rows imported from Excel.
#'
#' @param x A vector of any atomic type.
#'
#' @return A vector the same length and type as \code{x} with internal
#'   \code{NA}s replaced by the last preceding non-\code{NA} value.
#'
#' @examples
#' na_fill(c(NA, "A", NA, NA, "B", NA))
#' # [1] NA  "A" "A" "A" "B" "B"
#'
#' @keywords internal
na_fill <- function(x) {
  if (length(x) == 0) return(x)
  na_pos <- is.na(x)
  if (!any(na_pos)) return(x)
  # Walk through the vector once, carrying the last seen non-NA forward ----
  last <- x[NA_integer_][1]  # an NA of the appropriate type
  for (i in seq_along(x)) {
    if (!na_pos[i]) {
      last <- x[i]
    } else {
      x[i] <- last
    }
  }
  x
}


#' Clean column names and preserve originals as labels
#'
#' @description
#' Captures the current column names of a data frame, applies
#' \code{janitor::make_clean_names()} to produce syntactically valid R names,
#' and stores the original names as \code{label} attributes on each column.
#' This preserves the human-readable headings for use by labelling-aware
#' reporting packages (e.g. \pkg{reportRmd}, \pkg{gtsummary},
#' \pkg{labelled}) while letting downstream code refer to columns by tidy
#' names.
#'
#' @details
#' If a column already has a non-empty \code{label} attribute and
#' \code{overwrite = FALSE} (the default), the existing label is kept. Set
#' \code{overwrite = TRUE} to force replacement.
#'
#' @param data A data frame (or tibble).
#' @param overwrite Logical. If \code{TRUE}, replace any existing \code{label}
#'   attributes. If \code{FALSE} (default), only set labels on columns that
#'   don't already have one.
#' @param ... Additional arguments passed to \code{janitor::make_clean_names()}
#'   (e.g. \code{case = "snake"}).
#'
#' @return The input data frame with cleaned column names and \code{label}
#'   attributes set on each column.
#'
#' @examples
#' \dontrun{
#' df <- data.frame(`Patient ID` = 1:3, `Age at Diagnosis (yrs)` = c(45, 67, 52),
#'                  check.names = FALSE)
#' df <- set_names_as_labels(df)
#' names(df)
#' # [1] "patient_id" "age_at_diagnosis_yrs"
#' attr(df$patient_id, "label")
#' # [1] "Patient ID"
#' }
#'
#' @importFrom janitor make_clean_names
#' @export
set_names_as_labels <- function(data, overwrite = FALSE, ...) {
  if (!is.data.frame(data)) {
    stop("`data` must be a data frame.")
  }
  original_names <- names(data)
  new_names <- janitor::make_clean_names(original_names, ...)

  # Assign labels column-by-column, respecting existing labels when requested
  for (i in seq_along(data)) {
    existing <- attr(data[[i]], "label")
    has_label <- !is.null(existing) && length(existing) > 0 &&
                 !is.na(existing) && nzchar(existing)
    if (overwrite || !has_label) {
      attr(data[[i]], "label") <- original_names[i]
    }
  }
  names(data) <- new_names
  data
}


#' Convert a single column to Date if its values parse as dates
#'
#' @description
#' Runs the \code{parse_date()} / \code{clean_dates()} pipeline over a single
#' vector and returns the cleaned Date vector along with structured
#' diagnostic information.
#'
#' @param x A vector to convert.
#' @param var_name Character. Name of the variable, used as a label.
#'
#' @return A list with:
#'   \describe{
#'     \item{parsed}{The converted Date vector.}
#'     \item{n_errors}{Integer. Number of rows that failed to parse but had
#'       a non-empty original value.}
#'     \item{multiple_formats}{Logical. \code{TRUE} if more than one date
#'       format was detected.}
#'     \item{n_future_dates}{Integer. Count of parsed dates after today.}
#'     \item{error_values}{Character vector of the original values that
#'       failed to parse (deduplicated, capped at 10).}
#'   }
#'
#' @keywords internal
convert_column_to_date <- function(x, var_name = "column") {
  parsed_rows <- lapply(x, parse_date)
  dt_conversion <- dplyr::bind_rows(parsed_rows)
  cleaned <- suppressMessages(clean_dates(dt_conversion))

  # Rows where original was non-empty but parsed is NA = parse failures
  cd <- cleaned$cleaned_dates
  failed <- !is.na(cd$original) & nzchar(trimws(as.character(cd$original))) &
            is.na(cd$parsed)
  err_vals <- unique(as.character(cd$original[failed]))
  if (length(err_vals) > 10) err_vals <- c(err_vals[1:10], "...")

  list(
    parsed           = cd$parsed,
    n_errors         = sum(failed),
    multiple_formats = isTRUE(cleaned$multiple_formats),
    n_future_dates   = sum(cd$parsed > Sys.Date(), na.rm = TRUE),
    error_values     = err_vals
  )
}


#' Detect whether a column looks like it contains dates
#'
#' @description
#' Decides whether a column should be converted to \code{Date}. The decision
#' combines two signals:
#' \itemize{
#'   \item \strong{Name signal}: if \code{var_name} contains "date"
#'     (case-insensitive), the column is treated as a date column provided
#'     at least one sampled value parses successfully. This signal also
#'     applies to numeric columns - they are interpreted as Excel serial
#'     dates via \code{janitor::excel_numeric_to_date()}.
#'   \item \strong{Content signal}: for character columns only, if every
#'     sampled non-\code{NA} value parses via \code{parse_date()}, the
#'     column is treated as a date column regardless of its name.
#' }
#' Numeric columns without a "date" name hint are never flagged because real
#' numeric data (measurements, counts, IDs) frequently contains 5-digit
#' values that \code{parse_date()} would interpret as Excel serial dates.
#' Columns already imported as \code{Date} or \code{POSIXt} are skipped, as
#' are logical columns.
#'
#' @details
#' The asymmetric thresholds reflect intent. A column literally named
#' something like "visit_date" was meant to hold dates, so a single
#' parseable value is enough to attempt conversion - per-row failures will
#' be surfaced by \code{convert_column_to_date()}. A column with no name
#' hint needs unanimous evidence to avoid grabbing arbitrary character
#' columns that happen to contain a date-looking value or two.
#'
#' @param x A vector to test.
#' @param var_name Optional character. The column's name; if it matches the
#'   regex \code{"date"} (case-insensitive) the name signal kicks in.
#' @param sample_size Integer. Maximum number of non-\code{NA} values to
#'   test. Default is \code{50}.
#'
#' @return Logical scalar.
#'
#' @keywords internal
looks_like_date <- function(x, var_name = NULL, sample_size = 50) {
  # Already a date class - nothing to detect ----
  if (inherits(x, c("Date", "POSIXt"))) return(FALSE)
  # Logical columns are never dates
  if (is.logical(x)) return(FALSE)

  name_signal <- !is.null(var_name) &&
                 length(var_name) == 1L &&
                 !is.na(var_name) &&
                 grepl("date", var_name, ignore.case = TRUE)

  # Numeric column: only consider if the name signals a date column.
  # parse_date() will interpret values as Excel serial dates.
  if (is.numeric(x)) {
    if (!name_signal) return(FALSE)
  } else if (!is.character(x)) {
    return(FALSE)
  }

  # Filter to non-empty, non-NA values for sampling ----
  if (is.character(x)) {
    non_na <- x[!is.na(x) & nzchar(trimws(x))]
  } else {
    non_na <- x[!is.na(x)]
  }
  if (length(non_na) == 0) return(FALSE)

  # Sample to keep detection cheap on large columns ----
  if (length(non_na) > sample_size) {
    non_na <- sample(non_na, sample_size)
  }

  parsed <- lapply(non_na, parse_date)
  fmts <- vapply(parsed, function(p) {
    if (is.null(p$format) || is.na(p$format)) NA_character_ else p$format
  }, character(1))
  parse_ok <- !is.na(fmts) & fmts != "error"

  # Name match: any value parses is enough; otherwise require unanimity ----
  if (name_signal) any(parse_ok) else all(parse_ok)
}


#' Import an Excel sheet without a data dictionary
#'
#' @description
#' Streamlined Excel importer for sheets that do not have a companion data
#' dictionary. Reads the sheet, cleans column names via
#' \code{set_names_as_labels()} (preserving original headings as \code{label}
#' attributes), and optionally scans columns for date-like content - both
#' character columns parseable by lubridate and numeric columns with a
#' "date" name hint (interpreted as Excel serial dates). Columns named in
#' \code{date_cols} are always converted, bypassing detection.
#'
#' @details
#' Date detection rules differ by column type. Character columns are
#' converted when every sampled value parses as a date, or when the column
#' name contains "date" (case-insensitive) and at least one sampled value
#' parses. Numeric columns are converted only when the column name contains
#' "date"; without that hint they are left untouched, because real numeric
#' data (lab values, IDs, counts) routinely contains values that look like
#' Excel date serials. Columns already imported as \code{Date} or
#' \code{POSIXct} by \pkg{readxl} are left untouched.
#'
#' To force conversion regardless of detection, pass the column names to
#' \code{date_cols}. Names must match the columns as they appear in the
#' Excel sheet (i.e. \emph{before} \code{clean_names()} is applied).
#'
#' @param data_file Character. Path to the Excel file.
#' @param data_sheet Character. Name of the sheet to read.
#' @param date_cols Character vector. Column names (as they appear in the
#'   Excel sheet) to force-convert to Date, bypassing detection. Default
#'   \code{NULL}.
#' @param na Character vector. Strings to interpret as missing values. Default
#'   is \code{c("", "na", "NA")}.
#' @param clean_names Logical. If \code{TRUE} (default), apply
#'   \code{set_names_as_labels()} so columns get tidy names with originals
#'   stored as labels.
#' @param detect_dates Logical. If \code{TRUE} (default), scan columns for
#'   date-like content and convert them to \code{Date}. See \strong{Details}
#'   for the conversion rules. Set to \code{FALSE} to skip auto-detection;
#'   \code{date_cols} is still honoured.
#' @param verbose Logical. If \code{TRUE} (default), emit progress messages.
#'
#' @return A tibble of class \code{importExcel_df}: the cleaned data frame
#'   with diagnostics attached as attributes. Use the accessors to retrieve
#'   them:
#'   \describe{
#'     \item{\code{import_warnings(x)}}{Warnings generated by \pkg{readxl}.}
#'     \item{\code{date_warnings(x)}}{Wide tibble of date-conversion
#'       issues.}
#'     \item{\code{date_detection(x)}}{Audit tibble showing which columns
#'       were considered for date conversion and the outcome.}
#'     \item{\code{converted_dates(x)}}{Character vector of column names
#'       that were converted to Date.}
#'     \item{\code{import_summary(x)}}{Per-variable summary of actions
#'       taken, suitable for \code{knitr::kable()}.}
#'   }
#'
#' @examples
#' \dontrun{
#' df <- read_excel_no_dictionary(
#'   data_file  = "path/to/data.xlsx",
#'   data_sheet = "Lab results"
#' )
#'
#' # df is the cleaned data frame; diagnostics live as attributes
#' converted_dates(df)
#' import_summary(df)
#'
#' # Force a column that wasn't auto-detected:
#' df <- read_excel_no_dictionary(
#'   data_file  = "data.xlsx",
#'   data_sheet = "Visits",
#'   date_cols  = c("DOB", "EnrollmentDay")
#' )
#' }
#'
#' @importFrom readxl read_excel excel_sheets
#' @export
read_excel_no_dictionary <- function(data_file,
                                     data_sheet,
                                     date_cols = NULL,
                                     na = c("", "na", "NA"),
                                     clean_names = TRUE,
                                     detect_dates = TRUE,
                                     verbose = TRUE) {

  # Validate inputs ----
  if (!file.exists(data_file)) {
    stop(sprintf("Data file not found: '%s'\nPlease check the file path.", data_file))
  }
  if (!data_sheet %in% readxl::excel_sheets(data_file)) {
    stop(sprintf("Sheet '%s' not found in '%s'.", data_sheet, data_file))
  }

  # Read the sheet with warning capture ----
  imported <- suppressMessages(read_excel_with_warnings(data_file, data_sheet, na))
  if (is.null(imported$data)) {
    stop(paste("Error reading the data:\n", imported$errorMsg))
  }
  new_data <- imported$data

  # Drop columns with empty headers ----
  to_rm <- which(grepl("^\\.{3}", names(new_data)))
  if (length(to_rm) > 0) {
    warning(paste(
      "Empty column name(s) found in column(s)",
      paste(to_rm, collapse = ", "),
      "- these columns will not be imported."
    ))
    new_data <- new_data[, -to_rm]
  }

  # Validate any user-specified date_cols ----
  if (length(date_cols) > 0) {
    missing_dt <- setdiff(date_cols, names(new_data))
    if (length(missing_dt) > 0) {
      warning(sprintf(
        "date_cols not found in data and will be ignored: %s",
        paste(missing_dt, collapse = ", ")
      ))
      date_cols <- intersect(date_cols, names(new_data))
    }
  }

  # Detect and convert date-like columns ----
  date_conversions <- NULL
  detection_audit  <- NULL
  converted_dates  <- character(0)

  # Build the list of columns to convert: user-forced + detected ----
  detect_results <- vapply(
    seq_along(new_data),
    function(i) {
      if (detect_dates) {
        looks_like_date(new_data[[i]], var_name = names(new_data)[i])
      } else {
        FALSE
      }
    },
    logical(1)
  )
  detected_cols <- names(new_data)[detect_results]
  to_convert    <- unique(c(date_cols, detected_cols))

  if (length(to_convert) > 0) {
    msg_if(verbose, "Converting date columns.....")
    for (v in to_convert) {
      forced <- v %in% date_cols
      result <- convert_column_to_date(new_data[[v]], var_name = v)
      new_data[[v]] <- result$parsed
      converted_dates <- c(converted_dates, v)

      # Audit row
      detection_audit <- dplyr::bind_rows(
        detection_audit,
        tibble::tibble(
          variable = v,
          source   = if (forced) "user-specified" else "auto-detected",
          converted = TRUE
        )
      )

      if (result$n_errors > 0 || result$multiple_formats || result$n_future_dates > 0) {
        date_conversions <- dplyr::bind_rows(
          date_conversions,
          tibble::tibble(
            variable         = v,
            n_errors         = result$n_errors,
            multiple_formats = result$multiple_formats,
            n_future_dates   = result$n_future_dates,
            error_values     = paste(result$error_values, collapse = ", ")
          )
        )
      }
    }
  }

  # Clean names and store originals as labels ----
  if (clean_names) {
    new_data <- set_names_as_labels(new_data)
    # Re-map any references to cleaned names so downstream lookups work
    if (length(converted_dates) > 0) {
      converted_dates <- janitor::make_clean_names(converted_dates)
    }
    if (!is.null(date_conversions)) {
      date_conversions$variable <- janitor::make_clean_names(date_conversions$variable)
    }
    if (!is.null(detection_audit)) {
      detection_audit$variable <- janitor::make_clean_names(detection_audit$variable)
    }
  }

  # One-line summary ----
  n_dt <- if (is.null(date_conversions)) 0L else nrow(date_conversions)
  msg_if(verbose, sprintf("Imported %d columns; %d column(s) converted to Date; %d date warning(s).",
                          ncol(new_data), length(converted_dates), n_dt))

  new_import_result(
    new_data,
    import_warnings = imported$warnings,
    date_warnings   = date_conversions,
    date_detection  = detection_audit,
    converted_dates = converted_dates
  )
}


# ---- Accessor functions for importExcel_df attributes ----
#
# These thin accessors hide the underlying `attr()` lookup so the attribute
# names remain implementation details. Each one returns NULL when the
# requested diagnostic is absent.

#' Retrieve readxl warnings collected during import
#' @param x A data frame returned by an importExcel reader function.
#' @return Character vector of warnings, or \code{NULL} if none.
#' @export
import_warnings <- function(x) attr(x, "import_warnings")

#' Retrieve a tibble of non-numeric values removed during numeric conversion
#' @param x A data frame returned by an importExcel reader function.
#' @return A tibble (\code{variable}, \code{values_removed}, \code{n}) or
#'   \code{NULL}.
#' @export
numeric_conversions <- function(x) attr(x, "numeric_conversions")

#' Retrieve a tibble of date-conversion warnings
#' @param x A data frame returned by an importExcel reader function.
#' @return A wide tibble (\code{variable}, \code{n_errors},
#'   \code{multiple_formats}, \code{n_future_dates}, \code{error_values})
#'   or \code{NULL}.
#' @export
date_warnings <- function(x) attr(x, "date_warnings")

#' Retrieve the date-detection audit
#'
#' Shows which columns were considered for date conversion and the source
#' of the decision (user-specified via \code{date_cols} or auto-detected).
#'
#' @param x A data frame returned by \code{read_excel_no_dictionary()}.
#' @return A tibble (\code{variable}, \code{source}, \code{converted}) or
#'   \code{NULL}.
#' @export
date_detection <- function(x) attr(x, "date_detection")

#' Retrieve the names of columns that were converted to Date
#' @param x A data frame returned by \code{read_excel_no_dictionary()}.
#' @return Character vector or \code{NULL}.
#' @export
converted_dates <- function(x) attr(x, "converted_dates")

#' Retrieve the resolved data dictionary
#' @param x A data frame returned by \code{read_excel_with_dictionary()}.
#' @return The dictionary tibble or \code{NULL}.
#' @export
import_dictionary <- function(x) attr(x, "import_dictionary")


#' Extract column labels from a data frame
#'
#' @description
#' Returns a tibble of column names and their \code{label} attributes.
#' Useful for inspecting labels set by \code{set_names_as_labels()} or
#' \code{reportRmd::set_labels()}, or for embedding a variable-label table
#' in a report.
#'
#' @param data A data frame.
#'
#' @return A tibble with columns \code{variable} and \code{label}. Columns
#'   with no label attribute show \code{NA}.
#'
#' @examples
#' \dontrun{
#' df <- read_excel_no_dictionary("data.xlsx", "Sheet1")
#' get_labels(df)
#' }
#'
#' @export
get_labels <- function(data) {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")
  lbls <- vapply(data, function(col) {
    l <- attr(col, "label")
    if (is.null(l)) NA_character_ else as.character(l)[1]
  }, character(1))
  tibble::tibble(variable = names(data), label = unname(lbls))
}


#' Per-variable summary of an import
#'
#' @description
#' Builds a tidy tibble summarising what happened to each variable during
#' import. Designed to be embedded directly in a report via
#' \code{knitr::kable()} or \code{gt::gt()}.
#'
#' @details
#' The summary combines information from the dictionary (when present),
#' the data classes after import, and the numeric/date conversion
#' diagnostics. Columns:
#' \describe{
#'   \item{variable}{Column name.}
#'   \item{label}{Column label, if set.}
#'   \item{type}{Resolved variable type: from the dictionary's \code{Type}
#'     field when available, otherwise inferred from the column class.}
#'   \item{action}{Short description of what the import did
#'     (e.g. "2 non-numeric values removed", "converted to Date",
#'     "factor with 3 levels", or "-" when no notable action was taken).}
#'   \item{n_issues}{Count of issues raised for the column (non-numeric
#'     coercions, date errors, future dates, etc.).}
#' }
#'
#' @param x A data frame returned by one of the importExcel reader
#'   functions.
#'
#' @return A tibble with one row per variable.
#'
#' @examples
#' \dontrun{
#' df <- read_excel_with_dictionary("data.xlsx", "Data", "Dict")
#' knitr::kable(import_summary(df))
#' }
#'
#' @export
import_summary <- function(x) {
  if (!is.data.frame(x)) stop("`x` must be a data frame.")

  # Base table from the data frame itself ----
  out <- tibble::tibble(
    variable = names(x),
    label    = vapply(x, function(col) {
      l <- attr(col, "label")
      if (is.null(l)) NA_character_ else as.character(l)[1]
    }, character(1)),
    type     = vapply(x, function(col) {
      if (inherits(col, "Date") || inherits(col, "POSIXt")) "Date"
      else if (is.factor(col)) "Categorical"
      else if (is.numeric(col)) "Numeric"
      else if (is.logical(col)) "Logical"
      else "Character"
    }, character(1)),
    action   = "-",
    n_issues = 0L
  )

  # Override type from the dictionary if available ----
  dict <- import_dictionary(x)
  if (!is.null(dict) && "Suggested_Name" %in% names(dict) && "Type" %in% names(dict)) {
    dict_lookup <- dict |>
      dplyr::filter(!is.na(Suggested_Name)) |>
      dplyr::select(Suggested_Name, Type) |>
      dplyr::distinct()
    out <- out |>
      dplyr::left_join(dict_lookup, by = c("variable" = "Suggested_Name")) |>
      dplyr::mutate(type = dplyr::coalesce(Type, type)) |>
      dplyr::select(-Type)
  }

  # Fill in factor level counts for categorical/coded columns ----
  for (i in seq_along(x)) {
    if (is.factor(x[[i]]) && out$action[i] == "-") {
      out$action[i] <- sprintf("factor with %d levels", length(levels(x[[i]])))
    }
    if (inherits(x[[i]], "Date") && out$action[i] == "-") {
      out$action[i] <- "converted to Date"
    }
  }

  # Layer in numeric conversion diagnostics ----
  nc <- numeric_conversions(x)
  if (!is.null(nc) && nrow(nc) > 0) {
    for (j in seq_len(nrow(nc))) {
      i <- which(out$variable == nc$variable[j])
      if (length(i) == 1) {
        out$action[i]   <- sprintf("%d non-numeric value(s) removed", nc$n[j])
        out$n_issues[i] <- nc$n[j]
      }
    }
  }

  # Layer in date warning diagnostics ----
  dw <- date_warnings(x)
  if (!is.null(dw) && nrow(dw) > 0) {
    for (j in seq_len(nrow(dw))) {
      i <- which(out$variable == dw$variable[j])
      if (length(i) == 1) {
        parts <- character(0)
        if (dw$n_errors[j] > 0)
          parts <- c(parts, sprintf("%d unparseable", dw$n_errors[j]))
        if (isTRUE(dw$multiple_formats[j]))
          parts <- c(parts, "mixed formats")
        if (dw$n_future_dates[j] > 0)
          parts <- c(parts, sprintf("%d future date(s)", dw$n_future_dates[j]))
        if (length(parts) > 0) {
          out$action[i]   <- paste("Date;", paste(parts, collapse = "; "))
          out$n_issues[i] <- dw$n_errors[j] + dw$n_future_dates[j]
        }
      }
    }
  }

  out
}


# ---- Dictionary scaffolding: data -> dictionary ----

#' Inspect variables in a data frame
#'
#' @description
#' Returns a tibble of per-variable metadata: position, name, label, class,
#' missingness, and unique-value count. Useful as a quick overview of an
#' imported data frame, and as the basis for \code{create_dictionary()}.
#'
#' @param data A data frame.
#'
#' @return A tibble with one row per column and the following columns:
#'   \describe{
#'     \item{column_number}{Position of the column in \code{data}.}
#'     \item{variable}{Column name.}
#'     \item{label}{The column's \code{label} attribute, or \code{NA}.}
#'     \item{type}{One of \code{"Date"}, \code{"Numeric"}, \code{"Logical"},
#'       \code{"Categorical"} (for factors), or \code{"Character"}.}
#'     \item{n_missing}{Number of \code{NA} values.}
#'     \item{n_unique}{Number of distinct non-\code{NA} values.}
#'     \item{all_missing}{\code{TRUE} if every value is \code{NA}.}
#'   }
#'
#' @examples
#' \dontrun{
#' df <- read_excel_no_dictionary("data.xlsx", "Sheet1")
#' get_var_info(df)
#' }
#'
#' @export
get_var_info <- function(data) {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")

  classify <- function(col) {
    if (inherits(col, "Date") || inherits(col, "POSIXt")) "Date"
    else if (is.factor(col)) "Categorical"
    else if (is.logical(col)) "Logical"
    else if (is.numeric(col)) "Numeric"
    else "Character"
  }

  tibble::tibble(
    column_number = seq_along(data),
    variable      = names(data),
    label         = vapply(data, function(col) {
      l <- attr(col, "label")
      if (is.null(l)) NA_character_ else as.character(l)[1]
    }, character(1)),
    type          = vapply(data, classify, character(1)),
    n_missing     = vapply(data, function(col) sum(is.na(col)), integer(1)),
    n_unique      = vapply(data, function(col) length(unique(col[!is.na(col)])), integer(1)),
    all_missing   = vapply(data, function(col) all(is.na(col)), logical(1))
  )
}


#' Drop uninformative columns from a data frame
#'
#' @description
#' Removes columns that carry no analytic value: columns where every value
#' is \code{NA}, and high-cardinality character/factor columns (free text)
#' where the number of distinct values exceeds \code{factor_limit}. Intended
#' as a preprocessing step before \code{create_dictionary()}.
#'
#' @param data A data frame.
#' @param factor_limit Integer. Character or factor columns with more than
#'   this many unique values are treated as free text and dropped. Default
#'   \code{10}.
#' @param verbose Logical. If \code{TRUE} (default), report what was
#'   dropped.
#'
#' @return The input data frame with uninformative columns removed.
#'
#' @examples
#' \dontrun{
#' df <- read_excel_no_dictionary("data.xlsx", "Sheet1")
#' df <- clean_data(df)
#' create_dictionary(df, "scaffolded.xlsx")
#' }
#'
#' @export
clean_data <- function(data, factor_limit = 10, verbose = TRUE) {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")
  info <- get_var_info(data)

  to_drop <- info$variable[info$all_missing]
  is_text_heavy <- info$type %in% c("Character", "Categorical") &
                   info$n_unique > factor_limit
  to_drop <- unique(c(to_drop, info$variable[is_text_heavy]))

  if (length(to_drop) > 0) {
    msg_if(verbose, sprintf("Dropping %d uninformative column(s): %s",
                            length(to_drop),
                            paste(to_drop, collapse = ", ")))
    data <- data[, setdiff(names(data), to_drop), drop = FALSE]
  } else {
    msg_if(verbose, "No uninformative columns to drop.")
  }
  data
}


#' Scaffold a data dictionary from a data frame
#'
#' @description
#' Writes a data dictionary in the schema expected by
#' \code{read_excel_with_dictionary()}. The dictionary captures each
#' column's original name, a tidy suggested name, a label, an inferred
#' type, and (for categorical columns) the observed levels. The user can
#' then edit the resulting \code{.xlsx} in Excel - typically to refine
#' labels, populate \code{Value_Label}, set \code{Import = FALSE} on
#' columns to skip - and re-import via \code{read_excel_with_dictionary()}.
#'
#' @details
#' Type is inferred from each column's class:
#' \itemize{
#'   \item Date or POSIXt columns -> \code{Date}
#'   \item Numeric columns -> \code{Numeric}
#'   \item Logical, factor, or character columns with at most
#'     \code{factor_limit} unique values -> \code{Categorical} (with one
#'     row per observed level)
#'   \item Character columns with more than \code{factor_limit} unique
#'     values -> \code{Type} left blank (imported as character)
#' }
#'
#' If \code{data_sheet} is non-\code{NULL}, the data itself is written to
#' that sheet of the same workbook, so the resulting file is a complete
#' self-contained input for \code{read_excel_with_dictionary()}.
#'
#' \code{Label_For_Report} defaults to each column's \code{label} attribute
#' if one is present (as set by \code{set_names_as_labels()} or
#' \code{read_excel_no_dictionary()}), otherwise to the column name.
#' \code{Suggested_Name} defaults to a tidy version of the column name via
#' \code{janitor::make_clean_names()}.
#'
#' @param data A data frame to describe.
#' @param file Path for the output \code{.xlsx} file.
#' @param dictionary_sheet Character. Name of the dictionary sheet.
#'   Default \code{"Dictionary"}.
#' @param data_sheet Character or \code{NULL}. If non-\code{NULL}, the data
#'   is also written to a sheet of this name in the same workbook. Default
#'   \code{"Data"}.
#' @param factor_limit Integer. Columns with more than this many unique
#'   values are not enumerated as categorical. Default \code{10}.
#' @param verbose Logical. If \code{TRUE} (default), emit a summary message.
#'
#' @return Invisibly, the dictionary tibble that was written. Called for
#'   its side effect of writing \code{file}.
#'
#' @examples
#' \dontrun{
#' df <- read_excel_no_dictionary("raw.xlsx", "Sheet1")
#' df <- clean_data(df)
#' create_dictionary(df, "scaffolded.xlsx")
#'
#' # User edits scaffolded.xlsx in Excel to refine labels and value labels
#'
#' coded <- read_excel_with_dictionary(
#'   "scaffolded.xlsx",
#'   data_sheet = "Data",
#'   dictionary_sheet = "Dictionary"
#' )
#' }
#'
#' @importFrom writexl write_xlsx
#' @importFrom janitor make_clean_names
#' @export
create_dictionary <- function(data,
                              file,
                              dictionary_sheet = "Dictionary",
                              data_sheet = "Data",
                              factor_limit = 10,
                              verbose = TRUE) {
  if (!is.data.frame(data)) stop("`data` must be a data frame.")
  if (missing(file) || !nzchar(file)) {
    stop("`file` must be a valid output path.")
  }

  info <- get_var_info(data)

  # Build the dictionary one variable at a time ----
  rows <- vector("list", nrow(info))
  for (i in seq_len(nrow(info))) {
    v        <- info$variable[i]
    col_data <- data[[v]]
    cls      <- info$type[i]
    n_uniq   <- info$n_unique[i]
    label    <- if (is.na(info$label[i])) v else info$label[i]
    suggested <- janitor::make_clean_names(v)

    # Decide the schema Type from the inferred class ----
    if (cls == "Date") {
      schema_type <- "Date"
    } else if (cls == "Numeric") {
      schema_type <- "Numeric"
    } else if (cls == "Logical") {
      schema_type <- "Categorical"
    } else if (cls %in% c("Character", "Categorical") && n_uniq <= factor_limit) {
      schema_type <- "Categorical"
    } else {
      # Free text - leave Type blank so the importer treats it as character
      schema_type <- NA_character_
    }

    # Header row for this variable ----
    header <- tibble::tibble(
      Current_Variable_Name = v,
      Suggested_Name        = suggested,
      Label_For_Report      = label,
      Type                  = schema_type,
      Column_Number         = info$column_number[i],
      Import                = TRUE,
      Value                 = NA,
      Value_Label           = NA_character_
    )

    # For Categorical types: enumerate observed levels, one extra row each ----
    if (identical(schema_type, "Categorical")) {
      lvls <- sort(unique(col_data[!is.na(col_data)]))
      if (length(lvls) > 0) {
        # First level goes on the header row; remaining levels get continuation rows
        header$Value <- lvls[1]
        header$Value_Label <- NA_character_
        if (length(lvls) > 1) {
          cont <- tibble::tibble(
            Current_Variable_Name = NA_character_,
            Suggested_Name        = NA_character_,
            Label_For_Report      = NA_character_,
            Type                  = NA_character_,
            Column_Number         = NA_integer_,
            Import                = NA,
            Value                 = lvls[-1],
            Value_Label           = NA_character_
          )
          rows[[i]] <- dplyr::bind_rows(header, cont)
        } else {
          rows[[i]] <- header
        }
      } else {
        rows[[i]] <- header
      }
    } else {
      rows[[i]] <- header
    }
  }

  dictionary <- dplyr::bind_rows(rows)

  # Coerce Value to character for consistent Excel writing ----
  # (mixed numeric/character levels across variables would otherwise clash)
  dictionary$Value <- as.character(dictionary$Value)

  # Write the workbook ----
  sheets <- list()
  sheets[[dictionary_sheet]] <- dictionary
  if (!is.null(data_sheet)) {
    # writexl can't write Date-class with attributes cleanly across all types;
    # tibble handles the conversion safely.
    sheets[[data_sheet]] <- tibble::as_tibble(data)
  }
  writexl::write_xlsx(sheets, path = file)

  msg_if(verbose, sprintf(
    "Wrote dictionary for %d column(s) to '%s'%s. Edit and re-import with read_excel_with_dictionary().",
    nrow(info), file,
    if (!is.null(data_sheet)) sprintf(" (data on sheet '%s', dictionary on sheet '%s')",
                                       data_sheet, dictionary_sheet) else ""
  ))

  invisible(dictionary)
}
